from .destroy import WEBHOOK_DESTROY_SCHEMA
from .list import WEBHOOK_LIST_SCHEMA
from .partial_update import WEBHOOK_PARTIAL_UPDATE_SCHEMA
from .ping import WEBHOOK_PING_SCHEMA
from .retrieve import WEBHOOK_RETRIEVE_SCHEMA

__all__ = [
    "WEBHOOK_DESTROY_SCHEMA",
    "WEBHOOK_LIST_SCHEMA",
    "WEBHOOK_PARTIAL_UPDATE_SCHEMA",
    "WEBHOOK_PING_SCHEMA",
    "WEBHOOK_RETRIEVE_SCHEMA",
]
